services:
  backend:
    build: .
    container_name: currency-convertor-backend
    restart: always
    working_dir: /app
    command: ash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --reload --port 8000"
    ports:
      - "8000:8000"
    environment:
      - ENV=${ENV}
    env_file:
      - ${ENV_FILE}
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:16-alpine
    container_name: currency-convertor-postgres
    env_file:
      - ./configuration/.env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached
volumes:
  postgres_data:
    driver: local
